server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: student-service
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/student**
        - id: teacher-service
          uri: lb://TEACHER-SERVICE
          predicates:
            - Path=/teacher**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user**,/user**/{segment}
        - id: lecture-service
          uri: lb://LECTURE-SERVICE
          predicates:
            - Path=/lecture**,/lecture**/{segment}
        - id: api-management-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api-management**